import test from "tape";
import Card from "../src/Card";
import cardStates from "../src/constants/cardStates";

test("Card state", (t) => {
    t.plan(1);

    var card = new Card();

    t.equal(card.getState(), cardStates.BACK);
});

test("Card id should be generated by default", (t) => {
    t.plan(1);

    var card = new Card();

    t.equal(typeof card.getId(), 'string');
});

test("Card pairId", (t) => {
    t.plan(1);

    var card = new Card();

    t.equal(card.getPairId(), undefined);
});

test("Card pairId non-default", (t) => {
    t.plan(1);

    var card = new Card({
        pairId: '7'
    });

    t.equal(card.getPairId(), '7');
});

test("Card set state", (t) => {
    t.plan(1);

    var card = new Card();

    card.setState(cardStates.FACE);

    t.equal(card.getState(), cardStates.FACE);
});

test("Card flip", (t) => {
    t.plan(3);

    const card = new Card();

    t.equal(card.getState(), cardStates.BACK);

    card.flip();

    t.equal(card.getState(), cardStates.FACE);

    card.flip();

    t.equal(card.getState(), cardStates.BACK);
});
