import test from "tape";
import Player from "../src/Player";

test("Player id should be generated by default", (t) => {
    t.plan(1);

    var player = new Player();

    t.equal(typeof player.getId(), 'string');
});
